//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string resim { get; set; }
        public string icerik { get; set; }

    }
}
