//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifler
    {
        public short Tarifid { get; set; }
        public string TarifAd { get; set; }
        public string TarifMalzeme { get; set; }
        public string TarifYapilis { get; set; }
        public string TarifResim { get; set; }
        public string TarifSahip { get; set; }
        public string TarifSahipMail { get; set; }
        public Nullable<bool> TarifDurum { get; set; }
    }
}
